openapi: 3.0.1
info:
  title: API de Transactions
  description: API pour gérer les transactions des utilisateurs 
  version: 1.0.2
paths:
  /transactions:
    get:
      summary: Liste des transactions de l'utilisateur
      description: Permet à un utilisateur authentifié de récupérer toutes ses transactions du mois en cours.
      security:
        - bearerAuth: []  # Authentification par token Bearer
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              examples:
                success:
                  value:
                    - transactionId: "12345"
                      description: "Achat de fournitures"
                      type: "debit"
                      amount: 50.75
                      date: "2025-01-09"
                    - transactionId: "12346"
                      description: "Vente de produit"
                      type: "credit"
                      amount: 120.50
                      date: "2025-01-08"
        '401':
          description: Utilisateur non authentifié
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Utilisateur non authentifié"
    post:
      summary: Ajouter une nouvelle transaction
      description: Permet à un utilisateur authentifié d'ajouter une nouvelle transaction.
      security:
        - bearerAuth: []  # Authentification par token Bearer
      requestBody:
        description: Informations nécessaires pour ajouter une transaction
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: "Achat de fournitures"
                type:
                  type: string
                  enum: [debit, credit]
                  example: "debit"
                amount:
                  type: number
                  format: float
                  example: 50.75
                date:
                  type: string
                  format: date
                  example: "2025-01-09"
      responses:
        '201':
          description: Transaction ajoutée avec succès
          content:
            application/json:
              examples:
                success:
                  value:
                    transactionId: "12347"
                    description: "Achat de fournitures"
                    type: "debit"
                    amount: 50.75
                    date: "2025-01-09"
        '400':
          description: Données invalides
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Données invalides"
        '401':
          description: Utilisateur non authentifié
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Utilisateur non authentifié"

  /transactions/{transactionId}:
    get:
      summary: Détails d'une transaction spécifique
      description: Retourne les détails d'une transaction pour un utilisateur authentifié.
      security:
        - bearerAuth: []  # Applique le mécanisme d'authentification pour cet endpoint
      parameters:
        - name: transactionId
          in: path
          required: true
          description: "ID unique de la transaction"
          schema:
            type: string
            example: "12345"
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              examples:
                success:
                  value:
                    transactionId: "12345"
                    description: "Achat de fournitures"
                    type: "debit"
                    amount: 50.75
                    date: "2025-01-09"
        '404':
          description: Transaction non trouvée
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Transaction non trouvée"
        '401':
          description: Utilisateur non authentifié
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Utilisateur non authentifié"
    put:
      summary: Modifier une transaction existante
      description: Permet à l'utilisateur de modifier certaines informations d'une transaction existante, à l'exception du montant et de l'id.
      security:
        - bearerAuth: []  # Applique le mécanisme d'authentification pour cet endpoint
      parameters:
        - name: transactionId
          in: path
          required: true
          description: "ID unique de la transaction"
          schema:
            type: string
            example: "12345"
      requestBody:
        description: Données nécessaires pour modifier la transaction
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: "Achat de fournitures - modifié"
                type:
                  type: string
                  enum: [debit, credit]
                  example: "debit"
      responses:
        '200':
          description: Transaction mise à jour avec succès
          content:
            application/json:
              examples:
                success:
                  value:
                    transactionId: "12345"
                    description: "Achat de fournitures - modifié"
                    type: "debit"
                    amount: 50.75  # Le montant ne change pas
                    date: "2025-01-10"
        '400':
          description: Données invalides
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Données invalides"
        '404':
          description: Transaction non trouvée
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Transaction non trouvée"
        '401':
          description: Utilisateur non authentifié
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Utilisateur non authentifié"
    delete:
      summary: Supprimer des informations d'une transaction
      description: Permet à l'utilisateur de supprimer certaines informations d'une transaction, comme la description ou les autres détails, mais **pas le montant** ni **l'id de la transaction**.
      security:
        - bearerAuth: []  # Applique le mécanisme d'authentification pour cet endpoint
      parameters:
        - name: transactionId
          in: path
          required: true
          description: "ID unique de la transaction"
          schema:
            type: string
            example: "12345"
      responses:
        '200':
          description: Informations de la transaction supprimées avec succès
          content:
            application/json:
              examples:
                success:
                  value:
                    description: "Achat de fournitures - modifié"
        '404':
          description: Transaction non trouvée
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Transaction non trouvée"
        '401':
          description: Utilisateur non authentifié
          content:
            application/json:
              examples:
                error:
                  value:
                    error: "Utilisateur non authentifié"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
